# Generated by Django 5.1 on 2024-10-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='image',
            field=models.ImageField(upload_to='affiliates'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='suscription',
            name='image',
            field=models.ImageField(upload_to='suscriptions'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(upload_to='tournaments'),
        ),
    ]
