# Generated by Django 5.1 on 2024-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_affiliate_image_alter_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
