# Generated by Django 5.1 on 2024-10-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_membership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affiliate',
            new_name='Product',
        ),
    ]
