# Generated by Django 5.1 on 2024-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_affiliate_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_receipt',
            field=models.ImageField(default=1, upload_to='memberships'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
