# Generated by Django 5.1 on 2024-10-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='suscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.suscription'),
        ),
    ]
