# Generated by Django 5.1 on 2024-10-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='membership',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.suscription'),
        ),
    ]
