# Generated by Django 5.1 on 2024-10-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_userprofile_membership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
