# Generated by Django 5.1 on 2024-10-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_membership_expiry_date_userprofile_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='suscription',
        ),
    ]
